// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0dx86psRdBrmxdC4vFpvPVg2YxSPaem0',
    appId: '1:187688016354:web:1df3fc88e5e6e78415c1bb',
    messagingSenderId: '187688016354',
    projectId: 'hangman-b80db',
    authDomain: 'hangman-b80db.firebaseapp.com',
    storageBucket: 'hangman-b80db.appspot.com',
    measurementId: 'G-HLG2ZYVDNN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgoQcWFYBa1pHFewYxykb54Z4ZncObp-A',
    appId: '1:187688016354:android:fa4e4de3225589f415c1bb',
    messagingSenderId: '187688016354',
    projectId: 'hangman-b80db',
    storageBucket: 'hangman-b80db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgC_ZSTWjVIxSEdLKHOg5ddxD7gxzLlQU',
    appId: '1:187688016354:ios:114c114fbd7f810615c1bb',
    messagingSenderId: '187688016354',
    projectId: 'hangman-b80db',
    storageBucket: 'hangman-b80db.appspot.com',
    iosClientId: '187688016354-r7nkmcg297qqkr0ibrv9rsi0lr6jdnei.apps.googleusercontent.com',
    iosBundleId: 'com.example.hangman',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgC_ZSTWjVIxSEdLKHOg5ddxD7gxzLlQU',
    appId: '1:187688016354:ios:114c114fbd7f810615c1bb',
    messagingSenderId: '187688016354',
    projectId: 'hangman-b80db',
    storageBucket: 'hangman-b80db.appspot.com',
    iosClientId: '187688016354-r7nkmcg297qqkr0ibrv9rsi0lr6jdnei.apps.googleusercontent.com',
    iosBundleId: 'com.example.hangman',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0dx86psRdBrmxdC4vFpvPVg2YxSPaem0',
    appId: '1:187688016354:web:008359c218692e1715c1bb',
    messagingSenderId: '187688016354',
    projectId: 'hangman-b80db',
    authDomain: 'hangman-b80db.firebaseapp.com',
    storageBucket: 'hangman-b80db.appspot.com',
    measurementId: 'G-8H9R6TWPQF',
  );
}
